### PR TITLE
App Store version

### PR DESCRIPTION
**Pull request by Fonta1n3**
This PR represents build 0.3.0 which is currently live on Testflight and "in review" for manual App Store release.

### CODE REVIEW

**Comment by ChristopherA** [comment]
LibWally is missing from Xcode project info. I am unable to build this version, I get the following errors:

```
/Users/christophera/Library/Developer/Xcode/DerivedData/QR_Vault-gsaefjeinospcvaaijnofxpdvijc/Build/Products/Release-iphoneos/LibWally.framework/Modules/LibWally.swiftmodule/arm64-apple-ios.swiftinterface:5:19: Underlying Objective-C module 'LibWally' not found
/Users/christophera/Library/Developer/Xcode/DerivedData/QR_Vault-gsaefjeinospcvaaijnofxpdvijc/Build/Products/Release-iphoneos/LibWally.framework/Modules/LibWally.swiftmodule/arm64-apple-ios.swiftinterface:206:74: No type named 'wally_tx_output' in module 'LibWally'
/Users/christophera/Library/Developer/Xcode/DerivedData/QR_Vault-gsaefjeinospcvaaijnofxpdvijc/Build/Products/Release-iphoneos/LibWally.framework/Modules/LibWally.swiftmodule/arm64-apple-ios.swiftinterface:217:73: No type named 'wally_tx_witness_stack' in module 'LibWally'
/Users/christophera/Library/Developer/Xcode/DerivedData/QR_Vault-gsaefjeinospcvaaijnofxpdvijc/Build/Products/Release-iphoneos/LibWally.framework/Modules/LibWally.swiftmodule/arm64-apple-ios.swiftinterface:279:73: No type named 'wally_tx_input' in module 'LibWally'
/Users/christophera/Documents/Workspace/GitHub/BlockchainCommons/bc-qr-vault-catalyst/QR Vault/Helpers/DeriveLifehash.swift:11:8: Failed to build module 'LibWally' from its module interface; the compiler that produced it, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)'
```

**Comment by ChristopherA** [comment]
Note also there is a merge conflict that needs to be resolved.

**Comment by shannona** [comment]
I think I ran into the same issue with Libwally:

When building for iOS Simulator, the expected library /Users/shannona/Documents/GitHub/BlockchainCommons/bc-qr-vault-catalyst/XCode/QR Vault/Frameworks/CLibWally.xcframework/ios-x86_64-simulator/libwallycore.a was not found in /Users/shannona/Documents/GitHub/BlockchainCommons/bc-qr-vault-catalyst/XCode/QR Vault/Frameworks/CLibWally.xcframework

**Comment by shannona** [comment]
The README conflict is likely because I changed QR Vault to UR Vault in the README.

**Comment by Fonta1n3** [comment]
@ChristopherA @shannona the latest commit should fix your build issue, it was the gitignore...

**Comment by Fonta1n3** [comment]
> The README conflict is likely because I changed QR Vault to UR Vault in the README.

can you fix it? when I submitted the PR there were no conflicts.

**Review by ChristopherA — APPROVED** [review]
Built and tested on M1 MacBook Air (2020) using MacOS Big Sur 11.3.1, with targets iPhone 11 Pro Max and M1 Mac (Designed for iPad).

**Pull request merged**
