### PR TITLE
Updated Financial Support & Added Questions

### PR DESCRIPTION
**Pull request by shannona**

### CODE REVIEW

**Comment by Fonta1n3** [comment]
ping @ChristopherA this one fell through the cracks it seems

**Review by ChristopherA — APPROVED** [review]
ACK

**Comment by shannona** [comment]
This should be mergeable now, @ChristopherA

**Comment by ChristopherA** [comment]
@shannona Can you resolve these conflicts?

**Comment by shannona** [comment]
All resolved. Should be OK to merge @ChristopherA

**Pull request merged**
